FROM golang:tip-alpine3.23 AS builder
WORKDIR /backend_go
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY ./docs ./docs/
COPY ./db ./db/
COPY ./cmd ./cmd/
COPY ./internal ./internal/
COPY ./pkg ./pkg/
RUN go build -o /server ./cmd/server/


FROM alpine:3.23.3
COPY --from=builder /server ./
CMD [ "./server" ]
EXPOSE 8080
HEALTHCHECK CMD "wget --tries=1 --no-verbose http://backend:8080/healthcheck || exit 1"
