// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comment (user_id, movie_id, text)
VALUES ($1, $2, $3)
RETURNING id, user_id, movie_id, text, created_at
`

type CreateCommentParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
	Text    string      `json:"text"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.UserID, arg.MovieID, arg.Text)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comment
WHERE user_id = $1 
  AND movie_id = $2
`

type DeleteCommentParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComment, arg.UserID, arg.MovieID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComment = `-- name: GetComment :one
SELECT id, user_id, movie_id, text, created_at
FROM comment
WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const getMovieCommentList = `-- name: GetMovieCommentList :many
SELECT id, user_id, text, created_at
FROM comment
WHERE movie_id = $1
`

type GetMovieCommentListRow struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Text      string           `json:"text"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetMovieCommentList(ctx context.Context, movieID pgtype.UUID) ([]GetMovieCommentListRow, error) {
	rows, err := q.db.Query(ctx, getMovieCommentList, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieCommentListRow
	for rows.Next() {
		var i GetMovieCommentListRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCommentList = `-- name: GetUserCommentList :many
SELECT id, movie_id, text, created_at
FROM comment
WHERE user_id = $1
`

type GetUserCommentListRow struct {
	ID        pgtype.UUID      `json:"id"`
	MovieID   pgtype.UUID      `json:"movie_id"`
	Text      string           `json:"text"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserCommentList(ctx context.Context, userID pgtype.UUID) ([]GetUserCommentListRow, error) {
	rows, err := q.db.Query(ctx, getUserCommentList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCommentListRow
	for rows.Next() {
		var i GetUserCommentListRow
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comment SET
  text = $2
WHERE id = $1 
RETURNING id, user_id, movie_id, text, created_at
`

type UpdateCommentParams struct {
	ID   pgtype.UUID `json:"id"`
	Text string      `json:"text"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Text)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
