// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorite.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFavorite = `-- name: CreateFavorite :one
INSERT INTO favorite(user_id, movie_id)
VALUES ($1, $2)
RETURNING user_id, movie_id
`

type CreateFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) CreateFavorite(ctx context.Context, arg CreateFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, createFavorite, arg.UserID, arg.MovieID)
	var i Favorite
	err := row.Scan(&i.UserID, &i.MovieID)
	return i, err
}

const deleteFavorite = `-- name: DeleteFavorite :execrows
DELETE FROM favorite
WHERE user_id = $1 
  AND movie_id = $2
`

type DeleteFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFavorite, arg.UserID, arg.MovieID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFavorite = `-- name: GetFavorite :one
SELECT user_id, movie_id
FROM favorite
WHERE movie_id = $1 
  AND user_id = $2
`

type GetFavoriteParams struct {
	MovieID pgtype.UUID `json:"movie_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetFavorite(ctx context.Context, arg GetFavoriteParams) (Favorite, error) {
	row := q.db.QueryRow(ctx, getFavorite, arg.MovieID, arg.UserID)
	var i Favorite
	err := row.Scan(&i.UserID, &i.MovieID)
	return i, err
}

const getMovieFavoriteList = `-- name: GetMovieFavoriteList :many
SELECT user_id
FROM favorite
WHERE movie_id = $1
`

func (q *Queries) GetMovieFavoriteList(ctx context.Context, movieID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getMovieFavoriteList, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFavoriteList = `-- name: GetUserFavoriteList :many
SELECT movie_id
FROM favorite
WHERE user_id = $1
`

func (q *Queries) GetUserFavoriteList(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserFavoriteList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var movie_id pgtype.UUID
		if err := rows.Scan(&movie_id); err != nil {
			return nil, err
		}
		items = append(items, movie_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
