// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movie_comment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovieComment = `-- name: CreateMovieComment :one
INSERT INTO movie_comment (user_id, movie_id, text)
VALUES ($1, $2, $3)
RETURNING id, user_id, movie_id, text, created_at
`

type CreateMovieCommentParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
	Text    string      `json:"text"`
}

func (q *Queries) CreateMovieComment(ctx context.Context, arg CreateMovieCommentParams) (MovieComment, error) {
	row := q.db.QueryRow(ctx, createMovieComment, arg.UserID, arg.MovieID, arg.Text)
	var i MovieComment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMovieComment = `-- name: DeleteMovieComment :execrows
DELETE FROM movie_comment
WHERE user_id = $1 
  AND movie_id = $2
`

type DeleteMovieCommentParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) DeleteMovieComment(ctx context.Context, arg DeleteMovieCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMovieComment, arg.UserID, arg.MovieID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMovieCommentList = `-- name: GetMovieCommentList :many
SELECT id, user_id, text, created_at
FROM movie_comment
WHERE movie_id = $1
`

type GetMovieCommentListRow struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Text      string           `json:"text"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetMovieCommentList(ctx context.Context, movieID pgtype.UUID) ([]GetMovieCommentListRow, error) {
	rows, err := q.db.Query(ctx, getMovieCommentList, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieCommentListRow
	for rows.Next() {
		var i GetMovieCommentListRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCommentList = `-- name: GetUserCommentList :many
SELECT id, movie_id, text, created_at
FROM movie_comment
WHERE user_id = $1
`

type GetUserCommentListRow struct {
	ID        pgtype.UUID      `json:"id"`
	MovieID   pgtype.UUID      `json:"movie_id"`
	Text      string           `json:"text"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserCommentList(ctx context.Context, userID pgtype.UUID) ([]GetUserCommentListRow, error) {
	rows, err := q.db.Query(ctx, getUserCommentList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCommentListRow
	for rows.Next() {
		var i GetUserCommentListRow
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovieComment = `-- name: UpdateMovieComment :one
UPDATE movie_comment SET
  text = $1
WHERE user_id = $2 
  AND movie_id = $3
RETURNING id, user_id, movie_id, text, created_at
`

type UpdateMovieCommentParams struct {
	Text    string      `json:"text"`
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) UpdateMovieComment(ctx context.Context, arg UpdateMovieCommentParams) (MovieComment, error) {
	row := q.db.QueryRow(ctx, updateMovieComment, arg.Text, arg.UserID, arg.MovieID)
	var i MovieComment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MovieID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
