// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateFavorite(ctx context.Context, arg CreateFavoriteParams) (Favorite, error)
	CreateMovie(ctx context.Context, title string) (Movie, error)
	CreateRating(ctx context.Context, arg CreateRatingParams) (Rating, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (UserDatum, error)
	DeleteComment(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteFavorite(ctx context.Context, arg DeleteFavoriteParams) (int64, error)
	DeleteMovie(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteRating(ctx context.Context, arg DeleteRatingParams) (int64, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error)
	GetComment(ctx context.Context, id pgtype.UUID) (Comment, error)
	GetFavorite(ctx context.Context, arg GetFavoriteParams) (Favorite, error)
	GetMovie(ctx context.Context, id pgtype.UUID) (GetMovieRow, error)
	GetMovieByTitle(ctx context.Context, title string) (GetMovieByTitleRow, error)
	GetMovieCommentList(ctx context.Context, movieID pgtype.UUID) ([]GetMovieCommentListRow, error)
	GetMovieFavoriteList(ctx context.Context, movieID pgtype.UUID) ([]pgtype.UUID, error)
	GetMovieList(ctx context.Context) ([]Movie, error)
	GetMovieRatingList(ctx context.Context, userID pgtype.UUID) ([]GetMovieRatingListRow, error)
	GetRating(ctx context.Context, arg GetRatingParams) (Rating, error)
	GetUser(ctx context.Context, id pgtype.UUID) (UserDatum, error)
	GetUserByLogin(ctx context.Context, login string) (UserDatum, error)
	GetUserCommentList(ctx context.Context, userID pgtype.UUID) ([]GetUserCommentListRow, error)
	GetUserFavoriteList(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	GetUserList(ctx context.Context) ([]UserDatum, error)
	GetUserRatingList(ctx context.Context, userID pgtype.UUID) ([]GetUserRatingListRow, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
	UpdateRating(ctx context.Context, arg UpdateRatingParams) (Rating, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UserDatum, error)
}

var _ Querier = (*Queries)(nil)
