// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rating.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRating = `-- name: CreateRating :one
INSERT INTO rating (user_id, movie_id, rating)
VALUES ($1, $2, $3)
RETURNING user_id, movie_id, rating
`

type CreateRatingParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
	Rating  int16       `json:"rating"`
}

func (q *Queries) CreateRating(ctx context.Context, arg CreateRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, createRating, arg.UserID, arg.MovieID, arg.Rating)
	var i Rating
	err := row.Scan(&i.UserID, &i.MovieID, &i.Rating)
	return i, err
}

const deleteRating = `-- name: DeleteRating :execrows
DELETE FROM rating
WHERE user_id = $1 
  AND movie_id = $2
`

type DeleteRatingParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) DeleteRating(ctx context.Context, arg DeleteRatingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRating, arg.UserID, arg.MovieID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMovieRatingList = `-- name: GetMovieRatingList :many
SELECT movie_id, rating
FROM rating
WHERE user_id = $1
`

type GetMovieRatingListRow struct {
	MovieID pgtype.UUID `json:"movie_id"`
	Rating  int16       `json:"rating"`
}

func (q *Queries) GetMovieRatingList(ctx context.Context, userID pgtype.UUID) ([]GetMovieRatingListRow, error) {
	rows, err := q.db.Query(ctx, getMovieRatingList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieRatingListRow
	for rows.Next() {
		var i GetMovieRatingListRow
		if err := rows.Scan(&i.MovieID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRating = `-- name: GetRating :one
SELECT user_id, movie_id, rating
FROM rating
WHERE user_id = $1 
  AND movie_id = $2
`

type GetRatingParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
}

func (q *Queries) GetRating(ctx context.Context, arg GetRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, getRating, arg.UserID, arg.MovieID)
	var i Rating
	err := row.Scan(&i.UserID, &i.MovieID, &i.Rating)
	return i, err
}

const getUserRatingList = `-- name: GetUserRatingList :many
SELECT movie_id, rating
FROM rating
WHERE user_id = $1
`

type GetUserRatingListRow struct {
	MovieID pgtype.UUID `json:"movie_id"`
	Rating  int16       `json:"rating"`
}

func (q *Queries) GetUserRatingList(ctx context.Context, userID pgtype.UUID) ([]GetUserRatingListRow, error) {
	rows, err := q.db.Query(ctx, getUserRatingList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRatingListRow
	for rows.Next() {
		var i GetUserRatingListRow
		if err := rows.Scan(&i.MovieID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRating = `-- name: UpdateRating :one
UPDATE rating SET
  rating = COALESCE($3, rating)
WHERE user_id = $1 
  AND movie_id = $2
RETURNING user_id, movie_id, rating
`

type UpdateRatingParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	MovieID pgtype.UUID `json:"movie_id"`
	Rating  *int16      `json:"rating"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, updateRating, arg.UserID, arg.MovieID, arg.Rating)
	var i Rating
	err := row.Scan(&i.UserID, &i.MovieID, &i.Rating)
	return i, err
}
